
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from './providers'
import { SessionProvider } from "next-auth/react";
import { getServerSession } from "next-auth";
// import { Poppins } from "next/font/google"

import Nav from "./components/Nav";
import { AuthProvider } from "./components/SessionProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"], // Specify the weights you want to use
//   variable: "--font-poppins", // Define a CSS variable for the font
// })

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider session={session}>
          <Providers>
            {/* <Nav /> */}
            {children}
          </Providers>
        </AuthProvider>
       
      </body>
    </html>
  );
}
